[package]
name = "soroban-liquidity-pool-contract"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["export"]
export = []
testutils = ["soroban-sdk/testutils", "soroban-token-contract/testutils", "dep:ed25519-dalek", "dep:sha2", "dep:stellar-xdr"]

[dependencies]
ed25519-dalek = { version = "1.0.1", optional = true }
sha2 = { version = "0.10.2", optional = true }
soroban-token-contract = { git = "https://github.com/stellar/soroban-token-contract", rev = "24b77fee", default-features = false  }
# soroban-token-contract = { path = "../../soroban-token-contract", default-features = false  }
soroban-sdk = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "32b76650" }
# soroban-sdk = { path = "../../rs-soroban-sdk/sdk" }
stellar-xdr = { git = "https://github.com/stellar/rs-stellar-xdr", rev = "94e01c7b", features = ["next", "std"], optional = true }

[dev_dependencies]
rand = { version = "0.7.3" }
soroban-liquidity-pool-contract = { path = ".", default-features = false, features = ["testutils"] }
