[package]
name = "soroban-liquidity-pool-contract"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["export"]
export = []
testutils = ["soroban-sdk/testutils", "soroban-token-contract/testutils", "dep:ed25519-dalek", "dep:sha2", "dep:stellar-xdr"]

[dependencies]
soroban-sdk = "0.0.3"
soroban-sdk-auth = "0.0.0"
soroban-token-contract = { version = "0.0.2", default-features = false }
stellar-xdr = { version = "0.0.1", features = ["next", "std"], optional = true }
ed25519-dalek = { version = "1.0.1", optional = true }
sha2 = { version = "0.10.2", optional = true }

[dev_dependencies]
soroban-env-host = { version = "0.0.3" }
soroban-sdk = { version = "0.0.3", features = ["testutils"] }
soroban-token-contract = { version = "0.0.2", default-features = false, features = ["testutils"] }
stellar-xdr = { version = "0.0.1", features = ["next", "std"] }
ed25519-dalek = { version = "1.0.1" }
sha2 = { version = "0.10.2" }
rand = { version = "0.7.3" }
