[workspace]
resolver = "2"

members = [
    "authorization",
    "hello_world",
    "increment",
    "custom_types",
    "cross_contract/contract_a",
    "cross_contract/contract_b",
    "liquidity_pool",
    "liquidity_pool_router",
    "single_offer",
    "single_offer_xfer_from",
    "single_offer_router",
    "events",
    "timelock",
    "token"
]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[patch.crates-io]
soroban-sdk = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "bf6b383e" }
soroban-spec = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "bf6b383e" }
soroban-auth = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "bf6b383e" }
soroban-sdk-macros = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "bf6b383e" }
soroban-env-common = { git = "https://github.com/stellar/rs-soroban-env", rev = "0a826765" }
soroban-env-guest = { git = "https://github.com/stellar/rs-soroban-env", rev = "0a826765" }
soroban-env-host = { git = "https://github.com/stellar/rs-soroban-env", rev = "0a826765" }
soroban-env-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "0a826765" }
soroban-native-sdk-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "0a826765" }
stellar-xdr = { git = "https://github.com/stellar/rs-stellar-xdr", rev = "cebf5259" }
wasmi = { package = "soroban-wasmi", git = "https://github.com/stellar/wasmi", rev = "a61b6df" }
