[package]
name = "stellar-sign-auth-ed25519"
version = "0.1.0"
edition = "2021"
publish = false
rust-version = "1.85.0"

[dependencies]
stellar-xdr = { version = "23.0.0", features = ["base64", "serde"] }
serde_json = "1.0.140"
ed25519-dalek = { version = "1.0.1" }
hex = "0.4.3"
sha2 = "0.10.8"
clap = { version = "4.5.37", features = ["derive"] }
