[package]
name = "soroban-liquidity-pool-router-contract"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["export"]
export = []
testutils = ["soroban-sdk/testutils", "soroban-token-contract/testutils","soroban-liquidity-pool-contract/testutils","dep:ed25519-dalek", "dep:sha2", "dep:stellar-xdr"]

[dependencies]
soroban-sdk = "0.0.4"
soroban-auth = "0.0.4"
soroban-token-contract = { path = "../token", version = "0.0.4", default-features = false }
soroban-liquidity-pool-contract = { path = "../liquidity_pool", version = "0.0.0", default-features = false }
ed25519-dalek = { version = "1.0.1", optional = true }
stellar-xdr = { version = "0.0.2", features = ["next", "std"], optional = true }
sha2 = { version = "0.10.2", optional = true }

[dev_dependencies]
soroban-sdk = { version = "0.0.4", features = ["testutils"] }
soroban-auth = { version = "0.0.4", features = ["testutils"] }
soroban-token-contract = { path = "../token", version = "0.0.4", default-features = false, features = ["testutils"] }
soroban-liquidity-pool-contract = { path = "../liquidity_pool", version = "0.0.0", default-features = false, features = ["testutils"] }
stellar-xdr = { version = "0.0.2", features = ["next", "std"] }
ed25519-dalek = { version = "1.0.1" }
sha2 = { version = "0.10.2" }
rand = { version = "0.7.3" }
