[package]
name = "soroban-groth16-verifier-bn254"
version = "0.0.0"
edition = "2021"
publish = false
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { version = "25.0.2" }

[dev-dependencies]
soroban-sdk = { version = "25.0.2", features = ["testutils"] }
ark-bn254 = { version = "0.5.0" }
ark-serialize = { version = "0.5.0" }
ark-ff = { version = "0.5.0" }
ark-ec = { version = "0.5.0" }

