[package]
name = "privacy-pools"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true, features = ["alloc"] }
zk = { path = "../../zk" }
lean-imt = { path = "../../lean-imt" }
poseidon = { path = "../../poseidon" }
ark-ff = { version = "0.4.2", default-features = false }
ark-bls12-381 = { version = "0.4.0", default-features = false }
num-bigint = { version = "0.4", default-features = false }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
ark-bls12-381 = { version = "0.4.0" }
ark-serialize = { version = "0.4.2" }
ark-ff = { version = "0.4.2" }
ark-ec = { version = "0.4.2" }
hex = { version = "0.4.3" }

[features]
default = []
test_hash = []
